"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fontawesome_svg_core_1 = require("@fortawesome/fontawesome-svg-core");
var free_solid_svg_icons_1 = require("@fortawesome/free-solid-svg-icons");
fontawesome_svg_core_1.library.add(free_solid_svg_icons_1.fas);
var Button_1 = require("./Button");
exports.Button = Button_1.default;
var Menu_1 = require("./Menu");
exports.Menu = Menu_1.default;
var Col_1 = require("./Col");
exports.Col = Col_1.default;
var Row_1 = require("./Row");
exports.Row = Row_1.default;
var Icon_1 = require("./Icon");
exports.Icon = Icon_1.default;
var Input_1 = require("./Input");
exports.Input = Input_1.default;
var config_provider_1 = require("./config-provider");
exports.Provider = config_provider_1.default;
//# sourceMappingURL=index.js.map